version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      otelc:
        aliases:
          - prometheus
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./etc/otel-collector-config.yaml:/conf/config.yaml
    ports:
      # - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "8889:8889" # Prometheus metrics exporter
    restart: on-failure
    container_name: otel-collector
    networks:
      otelc:
        aliases:
          - otel-collector